name: Disableadchievements
version: 1.3
main: me.jurian.disableadchievements.disableadchievements.Disableadchievements
authors: [Jurian]
description: A plugin preventing adchievements from appearing in the chat.
